project:
  name: quickstart-sitecore-xp
  regions:
    - us-east-1
  parameters:
    SitecoreS3Bucket: "sitecore-software"
    RootStackName: "myroot"
    QSS3BucketName: "tcat-quickstart-sitecore-xp-0y85ih2c"
    QSS3KeyPrefix: "quickstart-sitecore-xp/"
    LambdaZipsBucketName: ""
tests:
  virginia:
    template: ./templates/sitecore-xp-security.template.yaml
    regions:
      - us-east-1
