project:
  name: quickstart-sitecore-xp
  regions:
    - us-east-1
  parameters:
    SCPrefix: "sc-tb"
    SOLRCorePrefix: "sc-tb"
    SOLRUrl: "slor.com2"
    EnvironmentType: "dev"
    SCLogLevel: "information"
    CorsOrigins: "*"
    RootStackName: "myroot"
    SCS3Bucket: "tcat-quickstart-sitecore-xp-0y85ih2c"
    SCResourcesPrefix: "XP1/resourcefiles/"
    SCLicensePrefix: "/"
    CDDNSName: "cd.com"
    CMDNSName: "cm.com"
    ISDNSName: "id.com"
    IntDNS: "internal"
tests:
  virginia:
    template: ./templates/sitecore-xp-parameters.template.yaml
    regions:
      - us-east-1
