project:
  name: quickstart-sitecore-xp
  regions:
    - us-east-2
  parameters:
    VPCCIDR: 10.0.0.0/16
    PrivateSubnet1ACIDR: 10.0.0.0/19
    PrivateSubnet2ACIDR: 10.0.32.0/19
    PublicSubnet1CIDR: 10.0.128.0/20
    PublicSubnet2CIDR: 10.0.144.0/20
    AvailabilityZones: "$[taskcat_getaz_2]"
    AdminUser: StackAdmin
    AdminPassword: "$[taskcat_genpass_16]"
    DomainDNSName: example.com
    NumberOfRDGWHosts: 1
    RDGWInstanceType: t2.large
    RDGWCIDR: 0.0.0.0/0
    KeyPairName: override
    CDDNSName: 'sc-tb-cd.dylanowe.myinstance.com'
    CMDNSName: 'sc-tb-cm.dylanowe.myinstance.com'
    ISDNSName: 'sc-tb-id.dylanowe.myinstance.com'
    IntDNS: ''
    CDMinSize: 1
    CDMaxSize: 1
    CDDesiredCapacity: 1
    CDInstanceType: m4.large
    CDScalingMetric: ASGAverageCPUUtilization
    CDScalingMetricValue: 50
    CMMinSize: 1
    CMMaxSize: 1
    CMInstanceType: m4.large
    CMScalingMetric: ASGAverageCPUUtilization
    CMScalingMetricValue: 50
    SitecoreKeyPair: override
    SitecorePrefix: sc
    SitecoreS3Bucket: yourbucket
    SCResourcesPrefix: resources/
    SCLicensePrefix: license/
    SOLRCorePrefix: scsolr
    SOLRUrl: 'https://ss777029-b4xtdrfm-us-east-1-aws.searchstax.com/solr/'
    EnvironmentType: Production
    SCLogLevel: Information
    CorsOrigins: replace
    EmailNotifications: operator@example.com
    PubliclyAccessible: 'false'
    DBInstanceClass: db.m5.xlarge
    DBAutoMinorVersionUpgrade: 'false'
    SQLEngineEdition: sqlserver-se
    SQLEngineVersion: 14.00.3192.2.v1
    VolumeSize: 500
    VolumeType: gp2
    BackupRetentionPeriod: 1
    QSS3BucketName: "$[taskcat_autobucket]"
    QSS3KeyPrefix: quickstart-sitecore-xp/
    ExternalCertificateARN: 'override'
    CacheNodeType: cache.m3.large
    RedisPort: 6379
    EmailNotifications: user@example.com
    LambdaZipsBucketName: ''
tests:
  virginia:
    template: ./templates/sitecore-xp-master.template.yaml
    regions:
      - us-east-1
