AWSTemplateFormatVersion: 2010-09-09
Description: "Creates the redis"
Parameters:
  CacheNodeType:
    Type: String
    Default: cache.r5.large
  Engine: 
    Type: String
    Default: redis
  NumCacheNodes:
    Type: Number
    Default: 1

Resources:
  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref CacheNodeType
      Engine: !Ref Engine
      NumCacheNodes: !Ref NumCacheNodes