AWSTemplateFormatVersion: 2010-09-09
Description: "Creates the required parameters in Parameter Store"
Parameters:
  SCPrefix:
    Type: String
  SOLRCorePrefix:
    Type: String
  SOLRUrl:
    Type: String
  IntLBDNS:
    Type: String
  EnvironmentType:
    Type: String
  SCLogLevel:
    Type: String
  CorsOrigins:
    Type: String
  RootStackName:
    Type: String
  SCS3Bucket:
    Type: String
  SCResourcesPrefix:
    Type: String
  SCLicensePrefix:
    Type: String
Resources:
# Sitecore Installation
  CustomAmiName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/instance/ami/custom
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub Sitecore-CustomAMI-${RootStackName}
  SitecoreS3Bucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/s3bucket/name
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCS3Bucket
  S3ResourcePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/s3bucket/scresourcesprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCResourcesPrefix
  S3LicensePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/s3bucket/sclicenseprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCLicensePrefix
  S3CertificatePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/s3bucket/certificateprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub 'sitecore-certificates-${RootStackName}/'
  LocalResourcesPath:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/localresourcespath
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "c:\\resources"
  ExportRootCertName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/root/exportname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-RootCertificate"
  ExportInstanceCertName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/instance/exportname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-InstanceCertificate"
  RootCertFriendlyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/root/friendlyname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-RootCertificate"
  RootCertDnsNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/root/dnsnames
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "127.0.0.1"
  InstanceCertFriendlyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/instance/friendlyname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-InstanceCertificate"
  InstanceCertDnsNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/instance/dnsnames
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub "*.${AWS::Region}.compute.internal,*.${AWS::Region}.elb.amazonaws.com,127.0.0.1"
  CertStoreLocation:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/cert/storelocation
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "LocalMachine"
#Sitecore Configuration
  SitecorePrefix: # used for the sitecore software configuration
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/sitecoreprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCPrefix
  PasswordRecoveryUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/service/passwordrecoveryurl
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub https://${IntLBDNS}/contentmanagment
  allowedCorsOrigins:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/service/allowedCorsOrigins
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref CorsOrigins
  Environment:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/environment
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref EnvironmentType
  LogLevel:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/logLevel
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCLogLevel
  SolrCorePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/solrcoreprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SOLRCorePrefix
  SolrUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/solruri
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SOLRUrl
  prefix: # this should be able to be removed
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${RootStackName}/user/s3bucket/prefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "/"
Outputs:
  CustomAmiName:
    Description: The name of the Quick Start Sitecore custom AMI
    Value: !GetAtt CustomAmiName.Value
  SCLocalResourcePath:
    Description: The location of the Sitecore resources on the AMI
    Value: !GetAtt LocalResourcesPath.Value
  InstanceCertificateLocation:
    Description: Location of the certificate on the instance
    Value: !Join 
            - ''
            - - !GetAtt S3CertificatePrefix.Value
              - !GetAtt ExportInstanceCertName.Value
              - ".pfx"