AWSTemplateFormatVersion: 2010-09-09
Description: "Creates the required parameters in Parameter Store"
Parameters:
  SCPrefix:
    Type: String
  SOLRCorePrefix:
    Type: String
  SOLRUrl:
    Type: String
  EnvironmentType:
    Type: String
  SCLogLevel:
    Type: String
  CorsOrigins:
    Type: String
  SCQSPrefix:
    Type: String
  SCS3Bucket:
    Type: String
  SCResourcesPrefix:
    Type: String
  SCLicensePrefix:
    Type: String
  CDDNSName:
    Type: String
  CMDNSName:
    Type: String
  ISDNSName:
    Type: String
  IntDNS:
    Type: String
Conditions:
  CreateDevSolr: !Equals [!Ref 'SOLRUrl', '']
Resources:
# Sitecore Installation
  CustomAmiName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/instance/ami/custom
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub Sitecore-CustomAMI-${SCQSPrefix}
  SitecoreS3Bucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/s3bucket/name
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCS3Bucket
  S3ResourcePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/s3bucket/scresourcesprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCResourcesPrefix
  S3LicensePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/s3bucket/sclicenseprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCLicensePrefix
  S3CertificatePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/s3bucket/certificateprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub 'sitecore-certificates-${SCQSPrefix}/'
  LocalResourcesPath:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/localresourcespath
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "c:\\resources"
  LocalQuickStartResourcesPath:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/localqsresourcespath
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "c:\\quickstart\\scripts"
  ExportRootCertName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/root/exportname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-RootCertificate"
  ExportInstanceCertName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/instance/exportname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-InstanceCertificate"
  ExportCollectionSearchCertName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/collsearch/exportname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-CollSearchCertificate"
  RootCertFriendlyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/root/friendlyname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-RootCertificate"
  RootCertDnsNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/root/dnsnames
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "127.0.0.1"
  InstanceCertFriendlyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/instance/friendlyname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-InstanceCertificate"
  CollSearchCertFriendlyName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/collsearch/friendlyname
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "Sitecore-QuickStart-CollSearchCertificate"
  InstanceCertDnsNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/instance/dnsnames
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub '*.${IntDNS},127.0.0.1'
      # Value: !Sub "*.${AWS::Region}.sitecore.internal"
  CollSearchCertDnsNames:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/collsearch/dnsnames
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Sub 'collsearch.${IntDNS},127.0.0.1'
      # Value: !Sub "*.${AWS::Region}.sitecore.internal"
  CertStoreLocation:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/cert/storelocation
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: "LocalMachine"
#Sitecore Configuration
  SitecorePrefix: # used for the sitecore software configuration
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/sitecoreprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCPrefix
  ContDelDNS: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/cddns
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref CDDNSName
  ContMgmtDNS: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/cmdns
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref CMDNSName
  IdentityDNS: 
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/isdns
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref ISDNSName
  InternalDNS: # Defines the internal DNS name for R53
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/internaldns
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref IntDNS
  PasswordRecoveryUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/passwordrecoveryurl
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref CMDNSName
  allowedCorsOrigins:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/service/allowedCorsOrigins
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref CorsOrigins
  Environment:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/environment
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref EnvironmentType
  LogLevel:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/logLevel
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SCLogLevel
  SolrCorePrefix:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/solrcoreprefix
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !Ref SOLRCorePrefix
  SolrUrl: # The full URL for the Solr Server
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${SCQSPrefix}/user/solruri
      Description: Parameter for the Sitecore XP1 Quick Start
      Type: String 
      Value: !If [CreateDevSolr, !Sub 'https://solrdev.${IntDNS}:8983/solr', !Ref 'SOLRUrl']  # If no Solr URL provided, then create URL https:\\solrdev.internaldns, else use provided url
  # prefix: # this should be able to be removed
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: !Sub /${SCQSPrefix}/user/s3bucket/prefix
  #     Description: Parameter for the Sitecore XP1 Quick Start
  #     Type: String 
  #     Value: "/"
# Secrets Manager entries
  SQLAdminUser: # Used for RDS Master user
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqladmin
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqladminuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMessagingUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlmessaging
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmessaginguser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\`'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingEngineUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlprocessingengine
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingengineuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlReportingUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlreporting
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlreportinguser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlCoreUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlcore
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlcoreuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlSecurityUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlsecurity
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlsecurityuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMasterUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlmaster
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmasteruser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlWebUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlweb
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlwebuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlReferenceDataUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlreferencedata
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlreferencedatauser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlFormsUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlforms
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlformsuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlExmMasterUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlexmmaster
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlexmmasteruser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingPoolsUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlprocessingpools
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingpoolsuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingTasksUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlprocessingtasks
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingtasksuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlCollectionUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlcollection
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlcollectionuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMarketingAutomationUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sqlmarketingautomation
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmarketingautomationuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  ReportingServiceAPIKey: 
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-reportingserviceapikey
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "APIKey"
        PasswordLength: 32
        ExcludePunctuation: true
        IncludeSpace: false
  ClientSecret: 
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-clientsecret
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "secret"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false
  SitecoreIdentitySecret: 
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sitecoreidentitysecret
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "secret"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false
  SitecoreAdminPassword: # Admin username and password for Sitecore
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-sitecoreadmin
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "administrator"}'
        GenerateStringKey: "Password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  ExportCertPassword: # Password for the certificate Export
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${SCQSPrefix}-certpass
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"certificatename": "Export-Certificate"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false

Outputs:
  CustomAmiName:
    Description: The name of the Quick Start Sitecore custom AMI
    Value: !GetAtt CustomAmiName.Value
  SCLocalResourcePath:
    Description: The location of the Sitecore resources on the AMI
    Value: !GetAtt LocalResourcesPath.Value
  QSLocalResourcePath:
    Description: The name of the Quick Start Sitecore custom AMI
    Value: !GetAtt LocalQuickStartResourcesPath.Value
  InstanceCertificateLocation:
    Description: Location of the certificate on the instance
    Value: !Join 
            - ''
            - - !GetAtt S3CertificatePrefix.Value
              - !GetAtt ExportInstanceCertName.Value
              - ".pfx"