AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys required IAM resources as well as entries into Secrets Manager for use in the Sitecore deployment"
Parameters:
  SitecoreS3Bucket:
    Type: String
  RootStackName:
    Type: String
  QSS3BucketName:
    Type: String
  QSS3KeyPrefix:
    Type: String
  LambdaZipsBucketName:
    Type: String

Resources:
#Lambda IAM Policy
  ConvertCertificatesLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: Get-Certificate-S3
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: s3:GetObject
                  Resource: !Sub 'arn:aws:s3:::${SitecoreS3Bucket}/*'
          - PolicyName: Import-Delete-ACM
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: 
                    - acm:ImportCertificate
                    - acm:DeleteCertificate
                  Resource: '*'
          - PolicyName: Get-Secret-Value
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: secretsmanager:GetSecretValue
                  Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:*:secret:*'
          - PolicyName: Put-Delete-SSM-Parameter
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: 
                    - ssm:PutParameter
                    - ssm:GetParameter
                    - ssm:DeleteParameter
                  Resource: !Sub 'arn:aws:ssm:${AWS::Region}:*:parameter/*'
  CopyZipsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: lambda-copier
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${LambdaZipsBucketName}/${QSS3KeyPrefix}*'
#Create IAM Role for Instances
  SCInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Effect: Allow
        Version: 2012-10-17
      # ManagedPolicyArns:
      #   - !Ref SCInstancePolicy
      Policies:
        - 
          PolicyName: SCInstanceAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - 
                Effect: "Allow" ###################### This policy needs to be limited in scope ######################
                Action: "*"
                Resource: "*"
  SCInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SCInstanceRole



#Create Secrets Manager Resources
  SQLAdminUser: # Used for RDS Master user
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqladmin
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqladminuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMessagingUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlmessaging
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmessaginguser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\`'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingEngineUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlprocessingengine
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingengineuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlReportingUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlreporting
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlreportinguser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlCoreUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlcore
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlcoreuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlSecurityUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlsecurity
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlsecurityuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMasterUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlmaster
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmasteruser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlWebUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlweb
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlwebuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlReferenceDataUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlreferencedata
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlreferencedatauser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlFormsUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlforms
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlformsuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlExmMasterUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlexmmaster
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlexmmasteruser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingPoolsUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlprocessingpools
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingpoolsuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlProcessingTasksUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlprocessingtasks
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlprocessingtasksuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlCollectionUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlcollection
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlcollectionuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  SqlMarketingAutomationUser: #Sitecore SQL DB User
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sqlmarketingautomation
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "sqlmarketingautomationuser"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  ReportingServiceAPIKey: ###########################################  ?????
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-reportingserviceapikey
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "APIKey"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false
  ClientSecret: ###########################################  ?????
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-clientsecret
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "secret"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false
  SitecoreIdentitySecret: ###########################################  ?????
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sitecoreidentitysecret
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "none"}'
        GenerateStringKey: "secret"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false
  SitecoreAdminPassword: # Admin username and password for Sitecore
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-sitecoreadmin
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"username": "administrator"}'
        GenerateStringKey: "Password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        IncludeSpace: false
  ExportCertPassword: # Password for the certificate Export
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub sitecore-quickstart-${RootStackName}-certpass
      Description: Secrets for the Sitecore XP1 Quick Start
      GenerateSecretString:
        SecretStringTemplate: '{"certificatename": "Export-Certificate"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludePunctuation: true
        IncludeSpace: false

Outputs:
  SCInstanceRoleARN:
    Description: ARN for the Instance Role.
    Value: !GetAtt SCInstanceRole.Arn
  SCInstanceProfileARN:
    Description: ARN for the Instance Profile.
    Value: !GetAtt SCInstanceProfile.Arn
  SCInstanceProfileName:
    Description: Name of the Instance Profile.
    Value: !Ref SCInstanceProfile
  ConvertCertificatesLambdaRoleArn:
    Description: The role ARN for the Lambda function to convert and upload certs to ACM.
    Value: !GetAtt ConvertCertificatesLambdaRole.Arn
  CopyZipsRoleArn:
    Description: The role ARN for the Lambda function to copy Zip's to local S3 bucket for Lambda Functions.
    Value: !GetAtt CopyZipsRole.Arn